apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rehearse.fullname" . }}-config
  labels:
    {{- include "rehearse.labels" . | nindent 4 }}
data:
  JUDGE_PROVIDER: {{ .Values.config.judgeProvider | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
